/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "pzueakkasdqdkduoadxx"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB6dWVha2thc2RxZGtkdW9hZHh4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM5MDE0ODcsImV4cCI6MjA4OTQ3NzQ4N30.vzglD-VYgtScpyeAQAvLqJpsv5r1X_duigyQ-qCR8KA"